SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BC_240801_COKESAVOURYOURZEN_Retailer](
	[ID] INT NOT NULL,
	[Code] [VARCHAR](100) NOT NULL,
	[Text] [NVARCHAR](150) NOT NULL,
	[HaveMinSpend] [bit] NOT NULL,
 CONSTRAINT [PK_BC_240801_COKESAVOURYOURZEN_Retailer] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO