SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BC_240801_COKESAVOURYOURZEN_Account](
	[AccountID] [int] IDENTITY(1,1) NOT NULL,
	[AccountType] [nvarchar](250) NOT NULL,
	[Password] [varchar](250) NOT NULL,
 CONSTRAINT [PK_BC_240801_COKESAVOURYOURZEN_Account] PRIMARY KEY CLUSTERED 
(
	[AccountID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

INSERT INTO [BC_240801_COKESAVOURYOURZEN_Account]([AccountType], [Password])
VALUES ('ADMIN', 'AQAAAAEAACcQAAAAEF8HfWXg8lWajxUDwB8ae2gKXS7g/K/PNORAnzFZ4Hc0ESF/Xm13qVm1SMeZiv+qQQ==');

INSERT INTO [BC_240801_COKESAVOURYOURZEN_Account]([AccountType], [Password])
VALUES ('USER', 'AQAAAAEAACcQAAAAELXh9BBeFwpCgVlpK8JVIxmkaIhhVnbndFDR3EyAcLXPptHFNzlpx6dBSQWb5n+mjg==');

INSERT INTO [BC_240801_COKESAVOURYOURZEN_Account]([AccountType], [Password])
VALUES ('IdentityPW', 'f3b396r6-b95e-4z84-lde1-f475f42sa893');