SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BC_240801_COKESAVOURYOURZEN_Winners](
	[WinnerID] [int] IDENTITY(1,1) NOT NULL,
	[GroupName] [nvarchar](250) NOT NULL,
	[DateWon] [datetime] NOT NULL,
	[EntryID] [int] NOT NULL,
	[MobileNo] [varchar](250) NOT NULL,
	[NRIC_NoPrefix] [varchar](50) NOT NULL,
 CONSTRAINT [PK_BC_240801_COKESAVOURYOURZEN_Winners] PRIMARY KEY CLUSTERED 
(
	[WinnerID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[BC_240801_COKESAVOURYOURZEN_Winners]  WITH CHECK ADD  CONSTRAINT [FK_BC_240801_COKESAVOURYOURZEN_EntryID] FOREIGN KEY([EntryID])
REFERENCES [dbo].[BC_240801_COKESAVOURYOURZEN] ([EntryID])
GO

ALTER TABLE [dbo].[BC_240801_COKESAVOURYOURZEN_Winners] CHECK CONSTRAINT [FK_BC_240801_COKESAVOURYOURZEN_EntryID]
GO

