//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseContest_WebForms.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BaseEntities : DbContext
    {
        public BaseEntities()
            : base("name=BaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BC_240801_COKESAVOURYOURZEN> BC_240801_COKESAVOURYOURZEN { get; set; }
        public virtual DbSet<BC_240801_COKESAVOURYOURZEN_Account> BC_240801_COKESAVOURYOURZEN_Account { get; set; }
        public virtual DbSet<BC_240801_COKESAVOURYOURZEN_LOG> BC_240801_COKESAVOURYOURZEN_LOG { get; set; }
        public virtual DbSet<BC_240801_COKESAVOURYOURZEN_Retailer> BC_240801_COKESAVOURYOURZEN_Retailer { get; set; }
        public virtual DbSet<BC_240801_COKESAVOURYOURZEN_Winners> BC_240801_COKESAVOURYOURZEN_Winners { get; set; }
    }
}
