//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseContest_WebForms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC_240801_COKESAVOURYOURZEN_Winners
    {
        public int WinnerID { get; set; }
        public string GroupName { get; set; }
        public System.DateTime DateWon { get; set; }
        public int EntryID { get; set; }
        public string MobileNo { get; set; }
        public string NRIC_NoPrefix { get; set; }
    
        public virtual BC_240801_COKESAVOURYOURZEN BC_240801_COKESAVOURYOURZEN { get; set; }
    }
}
