//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseContest_WebForms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC_240801_COKESAVOURYOURZEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BC_240801_COKESAVOURYOURZEN()
        {
            this.BC_240801_COKESAVOURYOURZEN_Winners = new HashSet<BC_240801_COKESAVOURYOURZEN_Winners>();
        }
    
        public int EntryID { get; set; }
        public System.DateTime DateEntry { get; set; }
        public string MobileNo { get; set; }
        public string EntryText { get; set; }
        public bool IsValid { get; set; }
        public bool IsVerified { get; set; }
        public bool IsRejected { get; set; }
        public string Reason { get; set; }
        public string Response { get; set; }
        public string VerificationCode { get; set; }
        public int Chances { get; set; }
        public string EntrySource { get; set; }
        public string Name { get; set; }
        public string NRIC { get; set; }
        public string NRIC_NoPrefix { get; set; }
        public string ReceiptNo { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> DateResent { get; set; }
        public Nullable<System.DateTime> DateVerified { get; set; }
        public Nullable<System.DateTime> DateRejected { get; set; }
        public string Email { get; set; }
        public string Retailer { get; set; }
        public string FileLink { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BC_240801_COKESAVOURYOURZEN_Winners> BC_240801_COKESAVOURYOURZEN_Winners { get; set; }
    }
}
