//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseContest_WebForms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC_240801_COKESAVOURYOURZEN_Retailer
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Text { get; set; }
        public bool HaveMinSpend { get; set; }
    }
}
