//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseContest_WebForms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC_240501_COKENCP_LOG
    {
        public int LogID { get; set; }
        public System.DateTime LogDate { get; set; }
        public string Recipient { get; set; }
        public string LogType { get; set; }
        public string Content { get; set; }
        public string CreditsUsed { get; set; }
    }
}
